services:
  mosaik-sim:
    build: ./simulators
    container_name: mosaik-sim
    ports:
      - "5555:5555"
    dns:
      - 127.0.0.11  # DNS interno do Docker
      - 8.8.8.8     # DNS de fallback
    networks:
      - mosaik-net

  mosaik-master:
    build: ./master
    container_name: mosaik-master
    depends_on:
      - mosaik-sim
    volumes:
      - ./output:/app/output
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - mosaik-net

networks:
  mosaik-net:
    driver: bridge
